//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMonHoc.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string IDHoaDon { get; set; }
        public string IDMonAn { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
